
import { dbService } from './dbService';
import type { UpdateLog } from '../types';

const IGNORED_FILES = ['setup.sh', 'deploy.sh', 'server.cjs', '.env', 'node_modules'];

class UpdateService {
    
    private generateYAMLConfig(config: any): string {
        // Simple manual YAML generation to avoid external deps
        let yaml = `version: "3.1.0"\nsystem:\n  name: "S.I.E."\n  env: "production"\n`;
        
        if (config.themeConfig) {
            yaml += `theme:\n`;
            Object.keys(config.themeConfig).forEach(k => {
                yaml += `  ${k}: "${config.themeConfig[k]}"\n`;
            });
        }
        
        if (config.homepageConfig) {
            yaml += `homepage:\n`;
            yaml += `  title: "${config.homepageConfig.title}"\n`;
            yaml += `  active: ${config.homepageConfig.active}\n`;
        }

        return yaml;
    }

    async generateSystemBackup() {
        const [theme, homepage, aiSettings] = await Promise.all([
            dbService.getTheme(),
            dbService.getHomepageConfig(),
            dbService.getAiAutomationSettings()
        ]);

        const fullConfig = {
            metadata: {
                timestamp: new Date().toISOString(),
                generator: "S.I.E. AutoUpdater v1.0"
            },
            themeConfig: theme,
            homepageConfig: homepage,
            aiSettings: aiSettings
        };

        return {
            json: JSON.stringify(fullConfig, null, 2),
            yaml: this.generateYAMLConfig(fullConfig)
        };
    }

    async runValidationCycle(onLog: (log: UpdateLog) => void): Promise<boolean> {
        onLog({ timestamp: new Date().toISOString(), message: "Iniciando ciclo de validação...", type: 'info' });
        
        // 1. Check DB Connection
        try {
            const dbStatus = await dbService.testConnection();
            if (dbStatus.status !== 'Conectado') {
                onLog({ timestamp: new Date().toISOString(), message: `ERRO CRÍTICO: Banco de Dados desconectado. ${dbStatus.details}`, type: 'error' });
                return false;
            }
            onLog({ timestamp: new Date().toISOString(), message: "Banco de Dados: OK", type: 'success' });
        } catch (e) {
            return false;
        }

        // 2. Validate Data Sources
        onLog({ timestamp: new Date().toISOString(), message: "Validando integridade das Fontes de Dados...", type: 'info' });
        await dbService.validateAllDataSources();
        onLog({ timestamp: new Date().toISOString(), message: "Fontes de Dados: OK", type: 'success' });

        // 3. Check Protected Files
        onLog({ timestamp: new Date().toISOString(), message: `Verificando arquivos protegidos: ${IGNORED_FILES.join(', ')}`, type: 'warning' });
        onLog({ timestamp: new Date().toISOString(), message: "Arquivos ignorados na verificação de reescrita para segurança.", type: 'info' });

        return true;
    }

    downloadFile(content: string, filename: string, mimeType: string) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    generateAutomationScript(): string {
        return `#!/bin/bash
# S.I.E. Automated Maintenance Script
# Generated by Auto-Updater

echo "--- Starting S.I.E. Maintenance Cycle ---"
date

# 1. Backup
echo "[1/4] Backing up database..."
if [ -f "sie_database.json" ]; then
    cp sie_database.json sie_database.backup_$(date +%F).json
fi

# 2. Health Check
echo "[2/4] Checking Node.js process..."
if pgrep -x "node" > /dev/null
then
    echo "Running"
else
    echo "Stopped. Restarting..."
    pm2 restart sie-backend
fi

# 3. Permissions
echo "[3/4] Fixing permissions..."
chown -R jennyai-sie:jennyai-sie .
chmod -R 755 .

# 4. Cleanup
echo "[4/4] Cleaning logs..."
pm2 flush

echo "--- Cycle Complete ---"
`;
    }
}

export const updateService = new UpdateService();
